import type { PG, Review } from "./types";

export const pgs: PG[] = [
  {
    id: "1",
    name: "The Maple House",
    city: "Bengaluru",
    area: "Koramangala",
    image: "/images/pg-1.png",
    price: 12500,
    rating: 4.8,
    reviewCount: 128,
    roomType: "Single",
    gender: "Any",
    amenities: ["WiFi", "Meals", "Housekeeping", "AC"],
    verified: true,
  },
  {
    id: "2",
    name: "Cedar Co-living",
    city: "Pune",
    area: "Baner",
    image: "/images/pg-2.png",
    price: 9800,
    rating: 4.6,
    reviewCount: 94,
    roomType: "Double sharing",
    gender: "Men",
    amenities: ["WiFi", "Gym", "Laundry", "Power backup"],
    verified: true,
  },
  {
    id: "3",
    name: "Willow Residency",
    city: "Hyderabad",
    area: "Gachibowli",
    image: "/images/pg-3.png",
    price: 14200,
    rating: 4.9,
    reviewCount: 156,
    roomType: "Co-living",
    gender: "Women",
    amenities: ["WiFi", "Meals", "Lounge", "Security"],
    verified: true,
  },
  {
    id: "4",
    name: "Aspen Studios",
    city: "Mumbai",
    area: "Powai",
    image: "/images/pg-4.png",
    price: 18500,
    rating: 4.7,
    reviewCount: 71,
    roomType: "Studio",
    gender: "Any",
    amenities: ["WiFi", "AC", "Kitchen", "Balcony"],
    verified: true,
  },
  {
    id: "5",
    name: "Birch Nest",
    city: "Delhi",
    area: "Hauz Khas",
    image: "/images/pg-5.png",
    price: 11000,
    rating: 4.5,
    reviewCount: 88,
    roomType: "Double sharing",
    gender: "Women",
    amenities: ["WiFi", "Meals", "Housekeeping", "Metro nearby"],
    verified: true,
  },
  {
    id: "6",
    name: "Juniper Heights",
    city: "Chennai",
    area: "Adyar",
    image: "/images/pg-6.png",
    price: 10500,
    rating: 4.6,
    reviewCount: 63,
    roomType: "Single",
    gender: "Men",
    amenities: ["WiFi", "AC", "Balcony", "Power backup"],
    verified: true,
  },
];

export const reviews: Review[] = [
  {
    id: "1",
    name: "Ananya Rao",
    location: "The Maple House, Bengaluru",
    rating: 5,
    text: "Moved in within a day of visiting. The room was exactly like the photos and the owner is genuinely helpful. Best decision I made this year.",
    initials: "AR",
  },
  {
    id: "2",
    name: "Rohit Menon",
    location: "Cedar Co-living, Pune",
    rating: 5,
    text: "Zero brokerage was real — I paid what was listed, nothing hidden. The common areas are clean and the WiFi actually works.",
    initials: "RM",
  },
  {
    id: "3",
    name: "Sneha Kapoor",
    location: "Willow Residency, Hyderabad",
    rating: 5,
    text: "As a woman moving to a new city, safety mattered most. The security and the community here made it feel like home instantly.",
    initials: "SK",
  },
  {
    id: "4",
    name: "Karthik Iyer",
    location: "Aspen Studios, Mumbai",
    rating: 4,
    text: "Loved having my own studio. The verification photos were accurate and move-in was smooth. Meals could have more variety though.",
    initials: "KI",
  },
  {
    id: "5",
    name: "Priya Nair",
    location: "Birch Nest, Delhi",
    rating: 5,
    text: "The reviews from real residents helped me pick with confidence. Everything matched. Highly recommend Nestly to anyone relocating.",
    initials: "PN",
  },
];

export const cities = [
  "Bengaluru",
  "Pune",
  "Hyderabad",
  "Mumbai",
  "Delhi",
  "Chennai",
];

export const areasByCity: Record<string, string[]> = {
  Bengaluru: ["Koramangala", "Indiranagar", "HSR Layout", "Whitefield"],
  Pune: ["Baner", "Hinjewadi", "Kothrud", "Viman Nagar"],
  Hyderabad: ["Gachibowli", "Madhapur", "Kondapur", "HITEC City"],
  Mumbai: ["Powai", "Andheri", "Bandra", "Thane"],
  Delhi: ["Hauz Khas", "Saket", "Dwarka", "Rohini"],
  Chennai: ["Adyar", "Velachery", "T. Nagar", "OMR"],
};
